# Generated by Django 3.2.1 on 2021-07-27 07:26

import app.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=30, verbose_name='Nom')),
                ('first_name', models.CharField(max_length=30, verbose_name='Prénom(s)')),
                ('gender', models.CharField(choices=[('h', 'Homme'), ('f', 'Femme')], max_length=1, verbose_name='Sexe')),
                ('work_place', models.CharField(max_length=50, verbose_name='Établissement')),
                ('job', models.CharField(max_length=100, verbose_name="Domaine d'études")),
                ('phone', models.CharField(max_length=30, unique=True, verbose_name='Téléphone')),
                ('email', models.CharField(max_length=30, unique=True, verbose_name='Courriel')),
                ('field', models.CharField(choices=[('licence', 'Licence'), ('master', 'Master'), ('doctorat', 'Doctorat')], max_length=10, verbose_name='Niveau')),
            ],
        ),
        migrations.CreateModel(
            name='QRCodeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=app.models.qr_path)),
                ('info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.contact')),
            ],
        ),
    ]
