# Generated by Django 3.2.1 on 2021-07-26 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='card_num',
        ),
    ]
